-- Verschiebt den Zusatztext der Info-Karte (Klick auf eine Preisposition)
-- von einem fest eincodierten Wörterbuch in index.html in die Datenbank,
-- damit er im Dashboard zusammen mit Name und Preis editierbar ist.

alter table public.service_price_items
  add column if not exists detail_copy text;

comment on column public.service_price_items.detail_copy is
  'Zusatztext in der Info-Karte beim Klick auf die Preisposition. NULL = Beschreibungstext der Behandlung wird stattdessen angezeigt.';

-- Bestehende Texte aus index.html als Startbestand übernehmen (nur wenn
-- noch kein Zusatztext gesetzt ist, damit spätere Admin-Änderungen nicht
-- überschrieben werden, falls diese Migration erneut läuft).
update public.service_price_items set detail_copy = 'Ein vollständiges Neuset mit Gel oder Acryl für ein natürliches, gepflegtes Ergebnis. Material, Länge und Form werden passend zu deinen Nägeln und deinem Stil gewählt.' where name = 'Neues Set Natural (Gel oder Acryl)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein vollständiges Neuset mit klarer French-Spitze oder einer deckenden Farbe. Form, Länge und Farbwirkung stimmen wir vor Beginn gemeinsam ab.' where name = 'Neues Set mit French oder Full Cover' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein individueller Akzent für einzelne Nägel – beispielsweise mit feinen Linien, Effekten oder dekorativen Details. Der angegebene Preis gilt pro gestaltetem Nagel.' where name = 'Nageldesign (pro Nagel)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die herausgewachsene Modellage wird sorgfältig aufgefüllt, neu ausbalanciert und in Form gebracht. Das Finish bleibt bewusst natürlich und gepflegt.' where name = 'Auffüllen Natural (Gel oder Acryl)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die bestehende Modellage wird aufgefüllt und mit einer neuen French-Gestaltung oder deckenden Farbe vollendet.' where name = 'Auffüllen mit French oder Full Cover' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine weich schattierte Augenbrauen-Pigmentierung mit sanftem Farbverlauf. Form, Farbton und gewünschte Intensität werden vor der Behandlung ausführlich abgestimmt.' where name = 'Ombré Augenbrauen' and detail_copy is null;
update public.service_price_items set detail_copy = 'Feine, haarähnliche Zeichnungen ergänzen und definieren die natürliche Brauenform. Die passende Linienführung und Farbe werden individuell vorgezeichnet.' where name = 'Microblading' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine zarte Lippenpigmentierung für eine harmonischere Kontur und einen frischen Farbeindruck. Farbton und Intensität werden persönlich ausgewählt.' where name = 'Aquarell Lippen' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine Pigmentierung entlang des oberen Wimpernkranzes, die je nach Wunsch dezent oder klarer ausgearbeitet wird. Stärke und Verlauf werden vorgezeichnet.' where name = 'Eyeliner oben' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine fein abgestimmte Pigmentierung am unteren Wimpernkranz. Ausdruck, Stärke und Verbindung zum oberen Lid werden individuell besprochen.' where name = 'Eyeliner unten' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine bestehende Permanent-Make-up-Arbeit wird hinsichtlich Farbe, Kontur und Gleichmässigkeit aufgefrischt. Der genaue Aufwand wird nach persönlicher Beurteilung festgelegt.' where name = 'Auffrischen (ab)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine klassische kosmetische Fusspflege mit sorgfältiger Pflege von Nägeln und Haut für ein sauberes, angenehm gepflegtes Ergebnis.' where name = 'Basis Pedicure' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die kosmetische Pedicure wird um ein entspannendes, intensiveres Pflegeritual ergänzt. Ideal, wenn neben gepflegten Füssen auch eine kleine Auszeit gewünscht ist.' where name = 'Spa Pedicure' and detail_copy is null;
update public.service_price_items set detail_copy = 'Kosmetische Fusspflege kombiniert mit einer haltbaren Gelmodellage der Zehennägel. Farbe und Finish werden passend zum gewünschten Look ausgewählt.' where name = 'Pedicure inkl. Gelnägel' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die Lippenbehandlung wird nach persönlicher Beratung auf Kontur, Proportion und das gewünschte Volumen abgestimmt. Eignung und Behandlungsumfang werden vorab sorgfältig geklärt.' where name = 'Lippen Filler' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine individuell geplante Behandlung zur sanften Betonung der Wangenpartie. Das gewünschte Ergebnis und der geeignete Umfang werden im Beratungsgespräch festgelegt.' where name = 'Wangen Filler' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die Behandlung wird gezielt auf den Bereich der Nasolabialfalten und die natürlichen Gesichtsproportionen abgestimmt. Grundlage ist immer eine persönliche Beratung.' where name = 'Nasolabialfalten' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine individuell geplante Behandlung zur harmonischen Betonung der Kinnkontur. Proportionen, Eignung und gewünschte Wirkung werden vorab gemeinsam beurteilt.' where name = 'Kinnkontur' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein persönliches Gespräch zu Wünschen, Möglichkeiten, Eignung und Behandlungsplanung. Bei anschliessender Behandlung wird der Beratungspreis angerechnet.' where name = 'Beratungsgespräch (wird bei Behandlung angerechnet)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine natürliche Wimpernverlängerung, bei der einzelne Extensions präzise gesetzt werden. Länge, Schwung und Wirkung passen wir an deine Augenform an.' where name = 'Neues Set Classic' and detail_copy is null;
update public.service_price_items set detail_copy = 'Feine Volumenfächer sorgen für ein sichtbar volleres, dennoch harmonisches Ergebnis. Dichte, Länge und Schwung werden individuell gewählt.' where name = 'Neues Set 4 bis 5D Volume' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein besonders ausdrucksstarker, dichter Wimpernlook mit individuell abgestimmten Volumenfächern. Die Ausführung bleibt auf Augenform und Tragekomfort abgestimmt.' where name = 'Neues Set Mega Volume' and detail_copy is null;
update public.service_price_items set detail_copy = 'Die natürlichen Wimpern werden angehoben und in einen gleichmässigen Schwung gebracht. Das Angebot befindet sich aktuell noch in Vorbereitung.' where name = 'Lash Lifting' and detail_copy is null;
update public.service_price_items set detail_copy = 'Herausgewachsene Classic-Extensions werden entfernt und entstandene Lücken fachgerecht aufgefüllt. Dieses Angebot gilt bis drei Wochen nach dem Neuset.' where name = 'Auffüllen Classic (bis 3 Wochen)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Das bestehende Volumenset wird kontrolliert, bereinigt und mit neuen 4- bis 5D-Fächern aufgefüllt. Gültig bis drei Wochen nach dem Neuset.' where name = 'Auffüllen 4 bis 5D (bis 3 Wochen)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Das Mega-Volume-Set wird sorgfältig aufgefrischt und wieder gleichmässig verdichtet. Dieses Angebot gilt bis drei Wochen nach dem Neuset.' where name = 'Auffüllen Mega Volume (bis 3 Wochen)' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein koreanisch inspiriertes Pflegeritual mit Fokus auf intensive Feuchtigkeit, ein verfeinertes Hautgefühl und sichtbar frische Ausstrahlung.' where name = 'Glass Skin Treatment' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine abgestimmte Gesichtspflege mit Fokus auf Ebenmässigkeit und Leuchtkraft. Produkte und Pflegeschritte werden passend zum aktuellen Hautbild gewählt.' where name = 'Brightening Facial' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein intensives Pflegeritual für anspruchsvolle Haut mit Fokus auf Feuchtigkeit, Pflege und ein glatter wirkendes Hautgefühl.' where name = 'Anti-Aging Ritual' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine gründliche Gesichtsreinigung, die auf Hautbild und aktuelle Bedürfnisse abgestimmt wird. Im Mittelpunkt stehen ein geklärtes und gepflegtes Hautgefühl.' where name = 'Deep Cleansing' and detail_copy is null;
update public.service_price_items set detail_copy = 'Eine intensive Feuchtigkeitsbehandlung mit aufeinander abgestimmten Pflegeschritten für praller und frischer wirkende Haut.' where name = 'Hyaluron Boost' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein leichtes, gepflegtes Make-up für Alltag, Business oder einen natürlichen Auftritt. Farben und Deckkraft werden an deinen Typ angepasst.' where name = 'Tages Make-up' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein ausdrucksstärkeres Make-up für den Abend mit abgestimmter Augen-, Teint- und Lippenwirkung. Der Look bleibt passend zu dir und deinem Anlass.' where name = 'Evening Look' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein haltbarer, fotografietauglicher Look für besondere Anlässe. Styling, Intensität und Farbstimmung werden auf Outfit und Event abgestimmt.' where name = 'Event Make-up' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein sorgfältig geplanter, lang anhaltender Braut-Look, der zu Persönlichkeit, Kleid und gewünschter Wirkung passt.' where name = 'Hochzeits Make-up' and detail_copy is null;
update public.service_price_items set detail_copy = 'Beim Probetermin entwickeln und testen wir den geplanten Look in Ruhe. Wünsche und Anpassungen können vor dem eigentlichen Anlass festgehalten werden.' where name = 'Probe Make-up' and detail_copy is null;
update public.service_price_items set detail_copy = 'Ein persönlicher Kurs zu Techniken, Produktauswahl und einem Look, den du selbst nachschminken kannst. Inhalte werden an Erfahrung und Ziele angepasst.' where name = 'Make-up Kurs' and detail_copy is null;
